---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: test
  labels:
    strimzi.io/cluster: test-cluster
spec:
  partitions: 10
  replicas: 3
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaUser
# metadata:
#   name: kafka-testing
#   labels:
#     strimzi.io/cluster: test-cluster
# spec:
#   authentication:
#     type: tls
#   authorization:
#     type: simple
#     acls:
#       # Example consumer Acls for topic my-topic using consumer group my-group
#       - resource:
#           type: topic
#           name: my-topic
#           patternType: literal
#         operations:
#           - Describe
#           - Read
#         host: "*"
#       - resource:
#           type: group
#           name: my-group
#           patternType: literal
#         operations:
#           - Read
#         host: "*"
#       # Example Producer Acls for topic my-topic
#       - resource:
#           type: topic
#           name: my-topic
#           patternType: literal
#         operations:
#           - Create
#           - Describe
#           - Write
#         host: "*"
